### PR TITLE
Ok I have reworked the code base quite a bit

### PR DESCRIPTION
**Pull request by screig**
The C++ projects had hard-coded links to specific installed versions of Postgres. I have made all the C++ projects use relative paths. I also went and tried to go and find the required references, namely the lib and include files for the following versions:

9.x x86
9.x x64
8.x x86
8.x x64 (this one I could not find)

I included this data in the code base (bar 8.x x64). I rebuilt the C++ projects which regenerated the missing dlls and copied them over to the C# folder.

### CODE REVIEW

**Comment by uzbekdev1** [comment]
🤗 thank you very much.


Thanks & regards,
*Elyor Latipov*.

*Mobile phone:*  <+998977111770>+998(97)711-17-70 <+998977111770>
*Job profile:*

   - http://www.linkedin.com/in/levdeo/
   - https://github.com/elyor0529/
   - https://bitbucket.org/levdeo/

*E-mail*:

   - elyor@outlook.com
   - elyor.blog@gmail.com

*IM:*

   - *Skype *- live:elyor
   - *Hangouts *- elyor.blog

**Comment by screig** [comment]
No probs, will want to add [Costura ](https://github.com/Fody/Costura) later to auto load the C++ dlss

**Comment by screig** [comment]
Is this going to accepted?

**Comment by uzbekdev1** [comment]
thx @screig

**Pull request merged**
